// Regenerates src/tools.gen.ts from Zo Computer's live MCP endpoint.
//
//   ZO_API_KEY=... npm run sync:mcp
//
// Fetches tools/list from https://api.zo.computer/mcp (or ZO_MCP_URL), writes
// a canonicalized snapshot to openapi/mcp-tools.json and the typed client to
// src/tools.gen.ts. Without credentials the script falls back to the
// checked-in snapshot so `npm run check` stays green in CI.

import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_BASE_URL } from '@/client.js';
import { emitToolsModule, type ToolDefinition } from './emitter.js';
import { canonicalizeTools } from './lib.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const SNAPSHOT_PATH = join(ROOT, 'openapi', 'mcp-tools.json');
const OUTPUT_PATH = join(ROOT, 'src', 'tools.gen.ts');

const BASE_URL = (process.env.ZO_MCP_URL ?? DEFAULT_BASE_URL).replace(/\/+$/, '');
const TOKEN = process.env.ZO_API_KEY ?? process.env.ZO_CLIENT_IDENTITY_TOKEN ?? '';

const HEADER = [
  '// This file is auto-generated by scripts/generate.ts from',
  "// openapi/mcp-tools.json (fetched from Zo Computer's MCP endpoint). Do not edit by hand.",
  '',
].join('\n');

let rpcId = 0;

// api.zo.computer/mcp never completes a streamable-HTTP `initialize`
// handshake, but it does serve `tools/list` as a stateless JSON-RPC POST
// (no session required). Fetch it directly instead of going through the SDK
// client so nightly sync can run without a live MCP session.
async function fetchLiveTools(): Promise<ToolDefinition[]> {
  const headers: Record<string, string> = {
    'content-type': 'application/json',
    accept: 'application/json, text/event-stream',
  };
  if (TOKEN) headers.authorization = `Bearer ${TOKEN}`;

  const tools: ToolDefinition[] = [];
  let cursor: string | undefined;
  do {
    const response = await fetch(BASE_URL, {
      method: 'POST',
      headers,
      signal: AbortSignal.timeout(60_000),
      body: JSON.stringify({
        jsonrpc: '2.0',
        id: ++rpcId,
        method: 'tools/list',
        params: cursor ? { cursor } : {},
      }),
    });
    const raw = await response.text();
    if (!response.ok) {
      throw new Error(`HTTP ${response.status} from ${BASE_URL}: ${raw.slice(0, 200)}`);
    }
    let payload: {
      result?: { tools?: ToolDefinition[]; nextCursor?: string };
      error?: { code?: number; message?: string };
    };
    try {
      payload = JSON.parse(raw);
    } catch {
      throw new Error(`non-JSON response from ${BASE_URL}: ${raw.slice(0, 200)}`);
    }
    if (payload.error) {
      throw new Error(`JSON-RPC ${payload.error.code}: ${payload.error.message}`);
    }
    tools.push(...(payload.result?.tools ?? []));
    cursor = payload.result?.nextCursor;
  } while (cursor);
  return tools;
}

async function readSnapshotTools(): Promise<ToolDefinition[]> {
  const raw = JSON.parse(await readFile(SNAPSHOT_PATH, 'utf8')) as { tools?: ToolDefinition[] };
  if (!Array.isArray(raw.tools) || raw.tools.length === 0) {
    throw new Error('snapshot has no tools');
  }
  // Snapshot order is irrelevant to codegen (the emitter sorts internally);
  // canonicalizing here keeps the regenerated client identical either way.
  return canonicalizeTools(raw.tools);
}

let tools: ToolDefinition[];
try {
  if (!TOKEN) throw new Error('no ZO_API_KEY / ZO_CLIENT_IDENTITY_TOKEN set');
  console.log(`Fetching tools/list from ${BASE_URL}...`);
  tools = await fetchLiveTools();
  // The MCP server returns tools (and their schema keys) in an arbitrary
  // order per request; canonicalize before writing so the nightly diff only
  // reflects real tool-definition changes, not response-order churn.
  tools = canonicalizeTools(tools);
  await writeFile(SNAPSHOT_PATH, JSON.stringify({ tools }, null, 2) + '\n', 'utf8');
  console.log(`Fetched ${tools.length} tools; snapshot updated.`);
} catch (err) {
  const reason = err instanceof Error ? err.message : String(err);
  if (!TOKEN) {
    console.warn(`No token; MCP sync skipped (${reason}). Using checked-in snapshot.`);
  } else {
    console.error(`MCP tools/list failed (${reason}). Falling back to checked-in snapshot.`);
  }
  tools = await readSnapshotTools();
  console.log(`Loaded ${tools.length} tools from snapshot.`);
}

await writeFile(OUTPUT_PATH, await emitToolsModule(tools, HEADER), 'utf8');
console.log(`Wrote ${OUTPUT_PATH}`);
