// This file is auto-generated by scripts/generate.ts from
// openapi/mcp-tools.json (fetched from Zo Computer's MCP endpoint). Do not edit by hand.

import { McpClientBase } from "./client.js";
import type { McpToolResult } from "./client.js";

export interface BashArgs {
    description?: string;
    cmd: string;
    cwd?: string;
    timeout?: number;
}

export interface CallMcpToolArgs {
    app_id: string;
    arguments: {
        [k: string]: unknown;
        };
    tool_name: string;
}

export interface ConnectIntegrationArgs {
    app_slug: string;
}

export interface ConnectTelegramArgs {
}

export interface CopyFileArgs {
    dest_path: string;
    source_path: string;
}

export interface CreateAgentArgs {
    delivery_method?: "email" | "sms" | "telegram" | "slack" | "discord" | "";
    instruction: string;
    model?: string;
    rrule: string;
}

export interface CreateAutomationArgs {
    delivery_method?: "email" | "sms" | "telegram" | "slack" | "discord" | "";
    instruction: string;
    model?: string;
    rrule: string;
}

export interface CreatePersonaArgs {
    image?: string;
    image_hue?: number;
    model?: string;
    name: string;
    prompt: string;
}

export interface CreateRuleArgs {
    condition?: string;
    instruction: string;
}

export interface CreateWebsiteArgs {
    force?: boolean;
    name: string;
    parent_path_parts?: string[];
    variant?: "blank" | "blog" | "event" | "slides" | "data" | "marketing" | "portfolio" | "kb" | "waitlist" | "storefront";
}

export interface DeleteAgentArgs {
    automation_id: string;
}

export interface DeleteAutomationArgs {
    automation_id: string;
}

export interface DeletePersonaArgs {
    persona_id: string;
}

export interface DeleteRuleArgs {
    rule_id: string;
}

export interface DeleteSpaceAssetArgs {
    /**
     * URL path of the asset to delete, e.g. '/images/logo.png'.
     */
    asset_path: string;
}

export interface DeleteSpaceRouteArgs {
    /**
     * Route path to delete, e.g. '/api/hello' or '/about'.
     */
    path: string;
}

export interface DeleteUserServiceArgs {
    service_id: string;
}

export interface EditAgentArgs {
    active?: "true" | "false" | "";
    automation_id: string;
    delivery_method?: "email" | "sms" | "telegram" | "slack" | "discord" | "none" | "";
    instruction?: string;
    model?: string;
    rrule?: string;
}

export interface EditAutomationArgs {
    active?: "true" | "false" | "";
    automation_id: string;
    delivery_method?: "email" | "sms" | "telegram" | "slack" | "discord" | "none" | "";
    instruction?: string;
    model?: string;
    rrule?: string;
}

export interface EditFileArgs {
    operations: {
        [k: string]: unknown;
        }[];
    target_file: string;
}

export interface EditFileLlmArgs {
    code_edit: string;
    instructions?: string;
    target_file: string;
}

export interface EditImageArgs {
    aspect_ratio?: "21:9" | "16:9" | "4:3" | "3:2" | "8:1" | "4:1" | "1:1" | "9:16" | "3:4" | "2:3" | "1:4" | "1:8" | "5:4" | "4:5";
    file_suffix?: string;
    filepaths?: string[] | null;
    mask_filepath?: string;
    model?: string;
    n?: number;
    prompt: string;
    provider?: "" | "openai" | "google";
    quality?: string;
    reference_filepaths?: string[] | null;
    size?: string;
    source_filepath?: string;
}

export interface EditPersonaArgs {
    /**
     * One short sentence describing what the edit does. Used with prompt_edit.
     */
    edit_instructions?: string;
    /**
     * New image URL for the avatar.
     */
    image?: string;
    /**
     * New HSL hue angle (0-360 integer) tinting the chrome Pegasus avatar. Anchors: 0=red, 60=yellow, 120=green, 180=cyan, 240=blue, 300=magenta (wraps at 360). Pass -1 to leave unchanged.
     */
    image_hue?: number;
    /**
     * AI model ID for the persona, if updating.
     */
    model?: string;
    /**
     * New display name, if renaming.
     */
    name?: string;
    /**
     * Identifier of the persona to update.
     */
    persona_id: string;
    /**
     * Edit to apply to the prompt. Provide only the changed sections, with '// ... existing content ...' placeholders for unchanged parts. Merged into the existing prompt via LLM. Strongly prefer additive edits.
     */
    prompt_edit?: string;
}

export interface EditRuleArgs {
    condition?: string;
    instruction?: string;
    rule_id: string;
}

export interface EditSpaceRouteArgs {
    /**
     * Partial edit — only the changed sections, with '// ... existing code ...' placeholders for unchanged parts. Merged against the current route code.
     */
    code_edit: string;
    /**
     * A sentence describing what the edit does, to help disambiguate. Leave empty to skip.
     */
    edit_instructions?: string;
    /**
     * Route path of the existing route to edit, e.g. '/about' or '/api/hello'.
     */
    path: string;
    /**
     * 'true' or 'false'. Optional visibility override for page routes. Leave empty to preserve current visibility. API routes are always public.
     */
    public?: string;
}

export interface FindSimilarLinksArgs {
    exclude_domains?: string[];
    exclude_source_domain?: boolean;
    include_domains?: string[];
    url: string;
}

export interface GenerateD2DiagramArgs {
    code: string;
    file_stem: string;
    output_dir?: string;
}

export interface GenerateImageArgs {
    aspect_ratio?: "21:9" | "16:9" | "4:3" | "3:2" | "8:1" | "4:1" | "1:1" | "9:16" | "3:4" | "2:3" | "1:4" | "1:8" | "5:4" | "4:5";
    file_stem: string;
    model?: string;
    n?: number;
    output_dir?: string;
    prompt: string;
    provider?: "" | "openai" | "google";
    quality?: string;
    reference_filepaths?: string[] | null;
    size?: string;
}

export interface GenerateSpeechArgs {
    file_stem: string;
    format?: "mp3" | "wav";
    instructions?: string;
    language?: string;
    model?: string;
    output_dir?: string;
    speed?: number;
    text: string;
    voice?: "ara" | "eve" | "leo" | "rex" | "sal";
    voice_sample_path?: string;
}

export interface GenerateVideoArgs {
    aspect_ratio?: "" | "1:1" | "16:9" | "9:16" | "4:3" | "3:4" | "3:2" | "2:3";
    duration_seconds?: number;
    end_frame_path?: string;
    file_stem?: string;
    file_suffix?: string;
    filepath?: string;
    generate_audio?: "auto" | "on" | "off";
    instruction: string;
    model?: string;
    orientation?: "landscape" | "portrait";
    output_dir?: string;
    resolution?: string;
}

export interface GetAutomationArgs {
    automation_id: string;
}

export interface GetSpaceErrorsArgs {
}

export interface GetSpaceRouteArgs {
    /**
     * Route path, e.g. '/api/hello' or '/about'.
     */
    path: string;
}

export interface GetSpaceRouteHistoryArgs {
    /**
     * Route path, e.g. '/about' or '/api/hello'.
     */
    path: string;
}

export interface GetSpaceSettingsArgs {
}

export interface GrepSearchArgs {
    case_sensitive?: boolean;
    exclude_pattern?: string;
    include_pattern?: string;
    location?: string;
    query: string;
    search_kind?: string;
}

export interface ImageSearchArgs {
    query: string;
}

export interface ListAgentsArgs {
}

export interface ListAppToolsArgs {
    app_slug: string;
}

export interface ListAutomationsArgs {
}

export interface ListAvailableScopesArgs {
}

export interface ListDirectoryArgs {
    ignore?: string[];
    path: string;
}

export interface ListPersonasArgs {
}

export interface ListRulesArgs {
}

export interface ListSpaceAssetsArgs {
}

export interface ListSpaceRoutesArgs {
}

export interface ListUserServicesArgs {
}

export interface MapsSearchArgs {
    included_type?: string;
    language?: string;
    location?: string;
    min_rating?: number;
    open_now?: "true" | "false" | "";
    price_level?: string;
    /**
     * Natural language prompt describing what to find on Google Maps.
     */
    query: string;
    region?: string;
}

export interface OpenMcpAppArgs {
    server_name: string;
    tool_name: string;
}

export interface OpenWebpageArgs {
    url: string;
}

export interface ProxyLocalServiceArgs {
    local_port: number;
}

export interface PublishSiteArgs {
    public?: "true" | "false" | "";
    site_path: string;
}

export interface ReadFileArgs {
    end_line?: number;
    pdf_epub_end_page_1_indexed_inclusive?: number;
    pdf_epub_include_images?: boolean;
    pdf_epub_start_page_1_indexed?: number;
    read_entire_file?: boolean;
    start_line?: number;
    target_file: string;
}

export interface ReadWebpageArgs {
    url: string;
    use_browser?: "true" | "false" | "";
}

export interface RedoSpaceRouteArgs {
    /**
     * Route path to redo, e.g. '/about' or '/api/hello'.
     */
    path: string;
}

export interface RegisterUserServiceArgs {
    entrypoint?: string;
    env_vars?: {
        [k: string]: unknown;
        };
    label: string;
    local_port?: number;
    mode: "http" | "tcp" | "process";
    public?: "true" | "false" | "";
    workdir?: string;
}

export interface RestartSpaceServerArgs {
}

export interface SaveWebpageArgs {
    url: string;
}

export interface SearchAppCatalogArgs {
    query: string;
}

export interface SendEmailToUserArgs {
    /**
     * Absolute file paths to attach (total size <= 10MB).
     */
    attachments?: string[];
    /**
     * Email body in Markdown. May be empty when attachments are provided.
     */
    markdown_body: string;
    /**
     * Email subject line. Must be non-empty.
     */
    subject: string;
}

export interface SendSmsToUserArgs {
    /**
     * Name of a registered contact. If omitted, sends to the user.
     */
    contact_name?: string;
    /**
     * Absolute file paths to send as MMS attachments.
     */
    media_files?: string[];
    /**
     * The text content. May be empty when media_files is provided.
     */
    message: string;
}

export interface ServiceDoctorArgs {
    service: string;
}

export interface SetActivePersonaArgs {
    persona_id: string;
}

export interface SetPersonaScopesArgs {
    /**
     * Identifier of the persona to update.
     */
    persona_id: string;
    /**
     * List of scope names (e.g. ['files:read', 'web:search']) or a
     */
    scopes: string[];
}

export interface ToolDocsArgs {
    tool_name: string;
}

export interface TranscribeAudioArgs {
    audio_file_path: string;
}

export interface TranscribeVideoArgs {
    video_file_path: string;
}

export interface UndoSpaceRouteArgs {
    /**
     * Route path to undo, e.g. '/about' or '/api/hello'.
     */
    path: string;
}

export interface UnpublishSiteArgs {
    site_path: string;
}

export interface UpdateSpaceAssetArgs {
    /**
     * URL path where the asset will be served, starting with '/', e.g. '/images/logo.png'.
     */
    asset_path: string;
    /**
     * Path to the source file in the workspace, e.g. '/home/workspace/images/logo.png'.
     */
    source_file: string;
}

export interface UpdateSpaceSettingsArgs {
    /**
     * AT Protocol DID for domain verification. Space-global only.
     */
    atproto_did?: string;
    /**
     * Route path for custom 404 page. Space-global only.
     */
    custom_404_route?: string;
    /**
     * HTML injected into <head>. Space-global only.
     */
    custom_head_html?: string;
    /**
     * Asset path for favicon. Space-global only.
     */
    favicon_url?: string;
    /**
     * HTML lang attribute value. Space-global only.
     */
    lang?: string;
    /**
     * "true" adds noindex/nofollow; "false" removes it; "default"
     */
    noindex?: "true" | "false" | "default" | "";
    /**
     * Asset path for OG image (e.g. "/assets/og.png"). Must
     */
    og_image_url?: string;
    /**
     * Empty string for space-global settings (default), or a route
     */
    path?: string;
    /**
     * Custom robots.txt content. Space-global only.
     */
    robots_txt?: string;
    /**
     * Meta description. Pass "default" to reset/clear.
     */
    site_description?: string;
    /**
     * Title override. Pass "default" to reset/clear.
     */
    site_title?: string;
}

export interface UpdateUserServiceArgs {
    enabled?: "true" | "false" | "";
    entrypoint?: string;
    env_vars?: {
        [k: string]: unknown;
        };
    label?: string;
    local_port?: number;
    mode?: "http" | "tcp" | "process" | "";
    public?: "true" | "false" | "";
    service_id: string;
    workdir?: string;
}

export interface UpdateUserSettingsArgs {
    field: "name" | "bio";
    value: string;
}

export interface UseAppGmailArgs {
    configured_props: {
        [k: string]: unknown;
        };
    download_path?: string;
    email?: string;
    tool_name: string;
}

export interface UseWebpageArgs {
    /**
     * Flat JSON-Schema-shaped grammar for a tool `output_schema` param.
     */
    output_schema?: {
        type: "object";
        properties: {
          [k: string]:
            | {
                type: "string" | "number" | "boolean";
                description?: string | null;
                enum?: string[] | null;
              }
            | {
                type: "array";
                description?: string | null;
                items:
                  | {
                      type: "string" | "number" | "boolean";
                      description?: string | null;
                      enum?: string[] | null;
                    }
                  | {
                      type: "object";
                      description?: string | null;
                      properties: {
                        [k: string]: {
                          type: "string" | "number" | "boolean";
                          description?: string | null;
                          enum?: string[] | null;
                        };
                      };
                      required?: string[];
                    };
              };
        };
        required?: string[];
        };
    task: string;
}

export interface ViewWebpageArgs {
}

export interface WebResearchArgs {
    category?: string;
    exclude_domains?: string[];
    include_domains?: string[];
    include_text?: string[];
    query: string;
    time_range?: string;
}

export interface WebSearchArgs {
    include_domains?: string[];
    query: string;
    time_range?: string;
    topic?: string;
}

export interface WriteFileArgs {
    content?: string;
    target_file: string;
}

export interface WriteSpaceRouteArgs {
    /**
     * Full source code for the route. Required — must be valid TypeScript/TSX with a default export.
     */
    code?: string;
    /**
     * Route path starting with '/'. Use '/' for custom home page. Any path works for either route type.
     */
    path: string;
    /**
     * 'true' or 'false'. Whether the route is publicly accessible. API routes are always public (this param is ignored). For pages, leave empty to preserve current visibility on updates; defaults to false for new non-homepage pages and true for the homepage (/).
     */
    public?: string;
    /**
     * Either 'api' or 'page'.
     */
    route_type: "api" | "page";
}

export interface XSearchArgs {
    allowed_x_handles?: string[];
    enable_image_understanding?: boolean;
    enable_video_understanding?: boolean;
    excluded_x_handles?: string[];
    from_date?: string;
    /**
     * Natural language prompt describing what to find on X.
     */
    query: string;
    time_range?: string;
    to_date?: string;
}

export const TOOL_NAMES = ["bash", "call_mcp_tool", "connect_integration", "connect_telegram", "copy_file", "create_agent", "create_automation", "create_persona", "create_rule", "create_website", "delete_agent", "delete_automation", "delete_persona", "delete_rule", "delete_space_asset", "delete_space_route", "delete_user_service", "edit_agent", "edit_automation", "edit_file", "edit_file_llm", "edit_image", "edit_persona", "edit_rule", "edit_space_route", "find_similar_links", "generate_d2_diagram", "generate_image", "generate_speech", "generate_video", "get_automation", "get_space_errors", "get_space_route", "get_space_route_history", "get_space_settings", "grep_search", "image_search", "list_agents", "list_app_tools", "list_automations", "list_available_scopes", "list_directory", "list_personas", "list_rules", "list_space_assets", "list_space_routes", "list_user_services", "maps_search", "open_mcp_app", "open_webpage", "proxy_local_service", "publish_site", "read_file", "read_webpage", "redo_space_route", "register_user_service", "restart_space_server", "save_webpage", "search_app_catalog", "send_email_to_user", "send_sms_to_user", "service_doctor", "set_active_persona", "set_persona_scopes", "tool_docs", "transcribe_audio", "transcribe_video", "undo_space_route", "unpublish_site", "update_space_asset", "update_space_settings", "update_user_service", "update_user_settings", "use_app_gmail", "use_webpage", "view_webpage", "web_research", "web_search", "write_file", "write_space_route", "x_search"] as const;

/**
 * Typed convenience methods for every tool Zo Computer exposes over MCP.
 * Generated by scripts/generate.ts — do not edit by hand.
 */
export class ZoComputerClient extends McpClientBase {
    /**
     * Run a single shell command on the computer.
     * Docs: https://docs.zocomputer.com/tools/bash.md
     */
    bash(args: BashArgs): Promise<McpToolResult> {
        return this.callTool("bash", args);
    }

    /**
     * Call a server tool through an open MCP App.
     * Docs: https://docs.zocomputer.com/tools/call-mcp-tool.md
     */
    callMcpTool(args: CallMcpToolArgs): Promise<McpToolResult> {
        return this.callTool("call_mcp_tool", args);
    }

    /**
     * Surface an inline Connect button so the user can authorize an OAuth integration.
     *
     * USE THIS whenever the user asks to do something with an OAuth integration
     * that is NOT yet connected for this workspace.  Five flavours, same
     * user-facing card:
     *
     * - Pipedream apps: ``gmail``, ``notion``, ``google_calendar``,
     *   ``google_tasks``, ``google_drive``, ``linear``, ``dropbox``,
     *   ``spotify``, ``google_sheets``, ``airtable_oauth``,
     *   ``microsoft_onedrive``, ``microsoft_outlook``.
     * - X (Twitter): pass ``app_slug="x"``.
     * - GitHub: pass ``app_slug="github"``. Opens a ``gh auth login``
     *   device-code dialog inline. Use this when the user wants GitHub
     *   access (PRs, repos, issues) and the workspace's gh CLI isn't
     *   authenticated yet — readiness is whether ``gh auth status`` passes.
     * - Stripe Connect: pass ``app_slug="stripe"``. Use this when the user
     *   wants to accept payments / sell products with Stripe and Stripe
     *   Connect isn't set up yet. The widget sends them to Settings →
     *   Integrations → Payments to finish onboarding (it does not run an
     *   inline OAuth flow). This is Zo's native Stripe integration — do NOT
     *   try to connect Stripe through the generic Pipedream catalog.
     * - OAuth MCP servers: pass ``app_slug="mcp:<slug>"`` — ``mcp:logfire``,
     *   ``mcp:sentry``, ``mcp:linear``, ``mcp:notion``, ``mcp:posthog``,
     *   ``mcp:cloudflare``, ``mcp:ahrefs``.
     * - Any other Pipedream catalog app: pass the ``app_slug`` from
     *   ``search_app_catalog`` results. The full 1000+ app catalog is
     *   connectable this way — not just the curated apps listed above.
     *
     * The ``mcp:`` prefix disambiguates MCP servers from Pipedream apps —
     * notably ``linear`` (Pipedream) is distinct from ``mcp:linear`` (the
     * Linear MCP server), and likewise ``notion`` vs ``mcp:notion``.
     *
     * Prefer this over telling the user to navigate to Settings — the inline
     * widget is one click vs. several, and looks better.
     *
     * The widget renders inline in chat.  When the user clicks Connect and
     * completes the OAuth round-trip, the connection is finalized automatically
     * and the widget flips to "Connected" — you do NOT need to wait for a tool
     * result or take any further action.  Your turn ends after you surface the
     * widget; connecting does NOT wake you back up.  Only on the user's *next
     * message* will your capabilities reflect the new connection state, at which
     * point you can proceed with the original request.
     *
     * After calling this tool, briefly acknowledge in chat that you've surfaced
     * a Connect button (one short sentence is enough — the widget speaks for
     * itself), and ask the user to let you know once they've connected so you
     * can continue.  Do NOT say or imply that clicking Connect will make you
     * automatically pick up where you left off ("once you connect, I'll
     * generate…") — that is misleading, because you stay idle until the user
     * sends another message.  Do not also link to Settings; the widget already
     * exposes that as an alternative.
     *
     * Do NOT call this tool if the app is already connected (check the
     * <capabilities> block) — that just clutters the chat with a redundant
     * card.  Do NOT call multiple times for the same `app_slug` in one turn.
     *
     * Note: ``linear`` / ``notion`` (Pipedream) and ``mcp:linear`` /
     * ``mcp:notion`` (MCP servers) are distinct integrations.  Use whichever
     * matches what the user asked for — if they're in MCP code mode or asked
     * for "the Linear MCP", use ``mcp:linear``; otherwise the Pipedream
     * ``linear`` is usually what they want.
     *
     * Do NOT use this for chat channels (Telegram, Discord) or AI model
     * providers (OpenAI, Anthropic, ...): Zo supports those natively — link the
     * user to the relevant settings page instead (Settings -> Channels or
     * Settings -> AI -> Providers).
     * Docs: https://docs.zocomputer.com/tools/connect-integration.md
     */
    connectIntegration(args: ConnectIntegrationArgs): Promise<McpToolResult> {
        return this.callTool("connect_integration", args);
    }

    /**
     * Generate a pairing code to connect Telegram to Zo.
     * Docs: https://docs.zocomputer.com/tools/connect-telegram.md
     */
    connectTelegram(args: ConnectTelegramArgs): Promise<McpToolResult> {
        return this.callTool("connect_telegram", args);
    }

    /**
     * Copy a file or directory on the computer.
     * Docs: https://docs.zocomputer.com/tools/copy-file.md
     */
    copyFile(args: CopyFileArgs): Promise<McpToolResult> {
        return this.callTool("copy_file", args);
    }

    /** Create an automation to run an AI task on a schedule. */
    createAgent(args: CreateAgentArgs): Promise<McpToolResult> {
        return this.callTool("create_agent", args);
    }

    /**
     * Create an automation to run an AI task on a schedule.
     * Docs: https://docs.zocomputer.com/tools/create-automation.md
     */
    createAutomation(args: CreateAutomationArgs): Promise<McpToolResult> {
        return this.callTool("create_automation", args);
    }

    /**
     * Create a new persona for Zo.
     * Docs: https://docs.zocomputer.com/tools/create-persona.md
     */
    createPersona(args: CreatePersonaArgs): Promise<McpToolResult> {
        return this.callTool("create_persona", args);
    }

    /**
     * Create a new user rule for Zo.
     * Docs: https://docs.zocomputer.com/tools/create-rule.md
     */
    createRule(args: CreateRuleArgs): Promise<McpToolResult> {
        return this.callTool("create_rule", args);
    }

    /**
     * Create a site (also known as an app, or a website).
     * Docs: https://docs.zocomputer.com/tools/create-website.md
     */
    createWebsite(args: CreateWebsiteArgs): Promise<McpToolResult> {
        return this.callTool("create_website", args);
    }

    /** Delete an existing automation. */
    deleteAgent(args: DeleteAgentArgs): Promise<McpToolResult> {
        return this.callTool("delete_agent", args);
    }

    /**
     * Delete an existing automation.
     * Docs: https://docs.zocomputer.com/tools/delete-automation.md
     */
    deleteAutomation(args: DeleteAutomationArgs): Promise<McpToolResult> {
        return this.callTool("delete_automation", args);
    }

    /**
     * Delete a persona by ID for the current user.
     * Docs: https://docs.zocomputer.com/tools/delete-persona.md
     */
    deletePersona(args: DeletePersonaArgs): Promise<McpToolResult> {
        return this.callTool("delete_persona", args);
    }

    /**
     * Delete a rule by ID.
     * Docs: https://docs.zocomputer.com/tools/delete-rule.md
     */
    deleteRule(args: DeleteRuleArgs): Promise<McpToolResult> {
        return this.callTool("delete_rule", args);
    }

    /**
     * Delete a static asset from the user's zo.space site.
     *
     * Args:
     *     asset_path: URL path of the asset to delete, e.g. '/images/logo.png'.
     * Docs: https://docs.zocomputer.com/tools/delete-space-asset.md
     */
    deleteSpaceAsset(args: DeleteSpaceAssetArgs): Promise<McpToolResult> {
        return this.callTool("delete_space_asset", args);
    }

    /**
     * Delete a route from the user's zo.space site.
     *
     * Args:
     *     path: Route path to delete, e.g. '/api/hello' or '/about'.
     * Docs: https://docs.zocomputer.com/tools/delete-space-route.md
     */
    deleteSpaceRoute(args: DeleteSpaceRouteArgs): Promise<McpToolResult> {
        return this.callTool("delete_space_route", args);
    }

    /**
     * Delete a managed user service on your Zo server.
     * Docs: https://docs.zocomputer.com/tools/delete-user-service.md
     */
    deleteUserService(args: DeleteUserServiceArgs): Promise<McpToolResult> {
        return this.callTool("delete_user_service", args);
    }

    /** Edit an existing automation's title, instruction, schedule, preferred communication channel, or model. */
    editAgent(args: EditAgentArgs): Promise<McpToolResult> {
        return this.callTool("edit_agent", args);
    }

    /**
     * Edit an existing automation's title, instruction, schedule, preferred communication channel, or model.
     * Docs: https://docs.zocomputer.com/tools/edit-automation.md
     */
    editAutomation(args: EditAutomationArgs): Promise<McpToolResult> {
        return this.callTool("edit_automation", args);
    }

    /**
     * Edit a text file using a sequence of precise edit operations.
     * Docs: https://docs.zocomputer.com/tools/edit-file.md
     */
    editFile(args: EditFileArgs): Promise<McpToolResult> {
        return this.callTool("edit_file", args);
    }

    /**
     * Merge a large or fuzzy rewrite into a text file using a fast apply LLM.
     * Docs: https://docs.zocomputer.com/tools/edit-file-llm.md
     */
    editFileLlm(args: EditFileLlmArgs): Promise<McpToolResult> {
        return this.callTool("edit_file_llm", args);
    }

    /**
     * Edit or combine workspace images with a compatible image model.
     * Docs: https://docs.zocomputer.com/tools/edit-image.md
     */
    editImage(args: EditImageArgs): Promise<McpToolResult> {
        return this.callTool("edit_image", args);
    }

    /**
     * Edit an existing persona — heavily biased toward additive, surgical changes.
     *
     * There is no full-replacement option here on purpose: a persona is the user's identity for the agent, and wholesale rewrites are almost always the wrong move. To create a brand-new persona, use create_persona instead.
     *
     * Prompt changes go through prompt_edit, which is merged into the existing prompt via an LLM. Use '// ... existing content ...' to leave large unchanged sections untouched. Almost all edits should be additive — appending a bullet, recording an observed preference, refining tone — rather than rewording or removing existing content. Never delete or shorten the prompt unless the user has explicitly asked you to.
     *
     * Args:
     *     persona_id: Identifier of the persona to update.
     *     name: New display name, if renaming.
     *     prompt_edit: Edit to apply to the prompt. Provide only the changed sections, with '// ... existing content ...' placeholders for unchanged parts. Merged into the existing prompt via LLM. Strongly prefer additive edits.
     *     edit_instructions: One short sentence describing what the edit does. Used with prompt_edit.
     *     image: New image URL for the avatar.
     *     image_hue: New HSL hue angle (0-360 integer) tinting the chrome Pegasus avatar. Anchors: 0=red, 60=yellow, 120=green, 180=cyan, 240=blue, 300=magenta (wraps at 360). Pass -1 to leave unchanged.
     *     model: AI model ID for the persona, if updating.
     * Docs: https://docs.zocomputer.com/tools/edit-persona.md
     */
    editPersona(args: EditPersonaArgs): Promise<McpToolResult> {
        return this.callTool("edit_persona", args);
    }

    /**
     * Edit an existing rule.
     * Docs: https://docs.zocomputer.com/tools/edit-rule.md
     */
    editRule(args: EditRuleArgs): Promise<McpToolResult> {
        return this.callTool("edit_rule", args);
    }

    /**
     * Edit an existing route's code by supplying only the changed sections.
     *
     * Preferred for edits to existing routes: sends only the changed sections with
     * `// ... existing code ...` placeholders for unchanged regions, merged against
     * the current route code.
     * Docs: https://docs.zocomputer.com/tools/edit-space-route.md
     */
    editSpaceRoute(args: EditSpaceRouteArgs): Promise<McpToolResult> {
        return this.callTool("edit_space_route", args);
    }

    /**
     * Find web pages similar to a given URL.
     * Docs: https://docs.zocomputer.com/tools/find-similar-links.md
     */
    findSimilarLinks(args: FindSimilarLinksArgs): Promise<McpToolResult> {
        return this.callTool("find_similar_links", args);
    }

    /**
     * Generate a block diagram, using D2.
     * Docs: https://docs.zocomputer.com/tools/generate-d2-diagram.md
     */
    generateD2Diagram(args: GenerateD2DiagramArgs): Promise<McpToolResult> {
        return this.callTool("generate_d2_diagram", args);
    }

    /**
     * Generate images with the host's default image model or an explicit compatible model.
     * Docs: https://docs.zocomputer.com/tools/generate-image.md
     */
    generateImage(args: GenerateImageArgs): Promise<McpToolResult> {
        return this.callTool("generate_image", args);
    }

    /**
     * Generate speech with a preset voice and save it in the workspace.
     * Docs: https://docs.zocomputer.com/tools/generate-speech.md
     */
    generateSpeech(args: GenerateSpeechArgs): Promise<McpToolResult> {
        return this.callTool("generate_speech", args);
    }

    /**
     * Generate a video from text, an optional start frame, or supported start and end frames.
     * Docs: https://docs.zocomputer.com/tools/generate-video.md
     */
    generateVideo(args: GenerateVideoArgs): Promise<McpToolResult> {
        return this.callTool("generate_video", args);
    }

    /**
     * Get full details of a single automation, including the complete instruction text.
     * Docs: https://docs.zocomputer.com/tools/get-automation.md
     */
    getAutomation(args: GetAutomationArgs): Promise<McpToolResult> {
        return this.callTool("get_automation", args);
    }

    /**
     * Get recent errors from the user's zo.space routes.
     *
     * Errors are logged when routes fail to load, build, or execute.
     * Also includes recent stderr output from the server.
     * Use this to debug issues with space routes.
     * Docs: https://docs.zocomputer.com/tools/get-space-errors.md
     */
    getSpaceErrors(args: GetSpaceErrorsArgs): Promise<McpToolResult> {
        return this.callTool("get_space_errors", args);
    }

    /**
     * Get a space route by path, including its source code.
     *
     * Use this to inspect the code of an existing route before editing it.
     *
     * Args:
     *     path: Route path, e.g. '/api/hello' or '/about'.
     * Docs: https://docs.zocomputer.com/tools/get-space-route.md
     */
    getSpaceRoute(args: GetSpaceRouteArgs): Promise<McpToolResult> {
        return this.callTool("get_space_route", args);
    }

    /**
     * View the full version history of a space route.
     *
     * Shows all versions (past and future relative to current position)
     * with action type and code preview. Use undo/redo to navigate.
     *
     * Args:
     *     path: Route path, e.g. '/about' or '/api/hello'.
     * Docs: https://docs.zocomputer.com/tools/get-space-route-history.md
     */
    getSpaceRouteHistory(args: GetSpaceRouteHistoryArgs): Promise<McpToolResult> {
        return this.callTool("get_space_route_history", args);
    }

    /**
     * Get space settings for the user's zo.space site.
     *
     * Returns the current settings (title, description, OG image, favicon, head HTML, robots.txt, etc).
     *
     * Args: (none)
     * Docs: https://docs.zocomputer.com/tools/get-space-settings.md
     */
    getSpaceSettings(args: GetSpaceSettingsArgs): Promise<McpToolResult> {
        return this.callTool("get_space_settings", args);
    }

    /**
     * Search files by content or filename using ripgrep.
     * Docs: https://docs.zocomputer.com/tools/grep-search.md
     */
    grepSearch(args: GrepSearchArgs): Promise<McpToolResult> {
        return this.callTool("grep_search", args);
    }

    /**
     * Search for images on the web using a search engine.
     * Docs: https://docs.zocomputer.com/tools/image-search.md
     */
    imageSearch(args: ImageSearchArgs): Promise<McpToolResult> {
        return this.callTool("image_search", args);
    }

    /** List all registered automations. */
    listAgents(args: ListAgentsArgs): Promise<McpToolResult> {
        return this.callTool("list_agents", args);
    }

    /**
     * List all available tools and configured props for an app connected by the user.
     * Docs: https://docs.zocomputer.com/tools/list-app-tools.md
     */
    listAppTools(args: ListAppToolsArgs): Promise<McpToolResult> {
        return this.callTool("list_app_tools", args);
    }

    /**
     * List all registered automations.
     * Docs: https://docs.zocomputer.com/tools/list-automations.md
     */
    listAutomations(args: ListAutomationsArgs): Promise<McpToolResult> {
        return this.callTool("list_automations", args);
    }

    /**
     * List all available tool permission scopes, presets, and requirement rules.
     * Docs: https://docs.zocomputer.com/tools/list-available-scopes.md
     */
    listAvailableScopes(args: ListAvailableScopesArgs): Promise<McpToolResult> {
        return this.callTool("list_available_scopes", args);
    }

    /**
     * Directory listing tool that shows files and subdirectories in a tree structure, helping you explore and understand the project organization.
     * Docs: https://docs.zocomputer.com/tools/list-directory.md
     */
    listDirectory(args: ListDirectoryArgs): Promise<McpToolResult> {
        return this.callTool("list_directory", args);
    }

    /**
     * List all personas for the user.
     * Docs: https://docs.zocomputer.com/tools/list-personas.md
     */
    listPersonas(args: ListPersonasArgs): Promise<McpToolResult> {
        return this.callTool("list_personas", args);
    }

    /**
     * List all rules for the user.
     * Docs: https://docs.zocomputer.com/tools/list-rules.md
     */
    listRules(args: ListRulesArgs): Promise<McpToolResult> {
        return this.callTool("list_rules", args);
    }

    /**
     * List all uploaded assets in the user's zo.space site.
     *
     * Returns the URL paths of all assets that can be referenced in pages.
     * Docs: https://docs.zocomputer.com/tools/list-space-assets.md
     */
    listSpaceAssets(args: ListSpaceAssetsArgs): Promise<McpToolResult> {
        return this.callTool("list_space_assets", args);
    }

    /**
     * List all routes in the user's zo.space site.
     * Docs: https://docs.zocomputer.com/tools/list-space-routes.md
     */
    listSpaceRoutes(args: ListSpaceRoutesArgs): Promise<McpToolResult> {
        return this.callTool("list_space_routes", args);
    }

    /**
     * List managed User Services running on your Zo server.
     * Docs: https://docs.zocomputer.com/tools/list-user-services.md
     */
    listUserServices(args: ListUserServicesArgs): Promise<McpToolResult> {
        return this.callTool("list_user_services", args);
    }

    /**
     * Search Google Maps for locations.
     *
     * This tool utilizes a subagent that uses the Google Maps API as a tool to search for locations following the provided query prompt.
     * Example use cases:
     * - Place-specific questions: "Is there a cafe near the corner of 1st and Main that has outdoor seating?"
     * - Finding the best locations by reviews: "Which family-friendly restaurants near here have the best playground reviews?"
     * - Itinerary planning: "Plan a day in San Francisco for me. I want to see the Golden Gate Bridge, visit a museum, and have a nice dinner."
     *
     * Args:
     *     query: Natural language prompt describing what to find on Google Maps.
     * Docs: https://docs.zocomputer.com/tools/maps-search.md
     */
    mapsSearch(args: MapsSearchArgs): Promise<McpToolResult> {
        return this.callTool("maps_search", args);
    }

    /**
     * Open an interactive MCP App inside web chat.
     * Docs: https://docs.zocomputer.com/tools/open-mcp-app.md
     */
    openMcpApp(args: OpenMcpAppArgs): Promise<McpToolResult> {
        return this.callTool("open_mcp_app", args);
    }

    /**
     * Open a webpage in Zo's browser.
     * Docs: https://docs.zocomputer.com/tools/open-webpage.md
     */
    openWebpage(args: OpenWebpageArgs): Promise<McpToolResult> {
        return this.callTool("open_webpage", args);
    }

    /**
     * Proxy a local service to a public endpoint using a TCP tunnel, similar to ngrok.
     * Docs: https://docs.zocomputer.com/tools/proxy-local-service.md
     */
    proxyLocalService(args: ProxyLocalServiceArgs): Promise<McpToolResult> {
        return this.callTool("proxy_local_service", args);
    }

    /**
     * Publish or republish a Zo Site so it gets a dedicated URL and runs a production build.
     * Docs: https://docs.zocomputer.com/tools/publish-site.md
     */
    publishSite(args: PublishSiteArgs): Promise<McpToolResult> {
        return this.callTool("publish_site", args);
    }

    /**
     * Read a file from the computer.
     * Docs: https://docs.zocomputer.com/tools/read-file.md
     */
    readFile(args: ReadFileArgs): Promise<McpToolResult> {
        return this.callTool("read_file", args);
    }

    /**
     * Read the content of a webpage.
     * Docs: https://docs.zocomputer.com/tools/read-webpage.md
     */
    readWebpage(args: ReadWebpageArgs): Promise<McpToolResult> {
        return this.callTool("read_webpage", args);
    }

    /**
     * Redo a previously undone change to a space route, restoring the next version.
     *
     * This can redo code changes and also redo deletions.
     * History persists across host reboots.
     *
     * Args:
     *     path: Route path to redo, e.g. '/about' or '/api/hello'.
     * Docs: https://docs.zocomputer.com/tools/redo-space-route.md
     */
    redoSpaceRoute(args: RedoSpaceRouteArgs): Promise<McpToolResult> {
        return this.callTool("redo_space_route", args);
    }

    /**
     * Register a managed User Service on your Zo server.
     * Docs: https://docs.zocomputer.com/tools/register-user-service.md
     */
    registerUserService(args: RegisterUserServiceArgs): Promise<McpToolResult> {
        return this.callTool("register_user_service", args);
    }

    /**
     * Stop zo.space, clean-install dependencies, rebuild, and start it again.
     *
     * Use when the space is crash-looping, serving stale content, or has corrupted dependencies.
     *
     * Args: (none)
     * Docs: https://docs.zocomputer.com/tools/restart-space-server.md
     */
    restartSpaceServer(args: RestartSpaceServerArgs): Promise<McpToolResult> {
        return this.callTool("restart_space_server", args);
    }

    /**
     * Save webpage content to the user's Articles directory.
     * Docs: https://docs.zocomputer.com/tools/save-webpage.md
     */
    saveWebpage(args: SaveWebpageArgs): Promise<McpToolResult> {
        return this.callTool("save_webpage", args);
    }

    /**
     * Search Pipedream's full catalog of 1000+ app integrations by keyword.
     *
     * Use this to find an integration that does NOT have a dedicated `use_app_*`
     * tool. Returns matching apps with their `app_slug`, name, and description,
     * plus whether the workspace has already connected each one.
     *
     * Catalog apps are beyond Zo's curated, verified set — they work, but Zo has
     * not tested them, so reliability varies. When a dedicated `use_app_*` tool
     * exists for what the user wants, prefer that.
     *
     * Once you've found an app:
     *   1. `connect_integration(app_slug)` — if it isn't connected yet.
     *   2. `list_app_tools(app_slug)` — see its actions and parameters.
     *   3. `use_integration(app_slug, tool_name, configured_props={...})`.
     * Docs: https://docs.zocomputer.com/tools/search-app-catalog.md
     */
    searchAppCatalog(args: SearchAppCatalogArgs): Promise<McpToolResult> {
        return this.callTool("search_app_catalog", args);
    }

    /**
     * Send an email to the user.
     *
     * Args:
     *     ctx: Runtime context.
     *     subject: Email subject line. Must be non-empty.
     *     markdown_body: Email body in Markdown. May be empty when attachments are provided.
     *     attachments: Absolute file paths to attach (total size <= 10MB).
     * Docs: https://docs.zocomputer.com/tools/send-email-to-user.md
     */
    sendEmailToUser(args: SendEmailToUserArgs): Promise<McpToolResult> {
        return this.callTool("send_email_to_user", args);
    }

    /**
     * Send an SMS text message to the user or a contact.
     *
     * Args:
     *     ctx: Runtime context.
     *     message: The text content. May be empty when media_files is provided.
     *     media_files: Absolute file paths to send as MMS attachments.
     *     contact_name: Name of a registered contact. If omitted, sends to the user.
     * Docs: https://docs.zocomputer.com/tools/send-sms-to-user.md
     */
    sendSmsToUser(args: SendSmsToUserArgs): Promise<McpToolResult> {
        return this.callTool("send_sms_to_user", args);
    }

    /**
     * Diagnose issues and get details about the status of a user_service.
     * Docs: https://docs.zocomputer.com/tools/service-doctor.md
     */
    serviceDoctor(args: ServiceDoctorArgs): Promise<McpToolResult> {
        return this.callTool("service_doctor", args);
    }

    /**
     * Set the active persona for the current channel (chat, SMS, email, etc.).
     * Docs: https://docs.zocomputer.com/tools/set-active-persona.md
     */
    setActivePersona(args: SetActivePersonaArgs): Promise<McpToolResult> {
        return this.callTool("set_active_persona", args);
    }

    /**
     * Set the tool permission scopes on a persona.
     *
     * Args:
     *     persona_id: Identifier of the persona to update.
     *     scopes: List of scope names (e.g. ['files:read', 'web:search']) or a
     *         single preset alias (e.g. ['all'], ['workspace'], ['read_only']).
     *         Pass an empty list for chat-only (no tools).
     * Docs: https://docs.zocomputer.com/tools/set-persona-scopes.md
     */
    setPersonaScopes(args: SetPersonaScopesArgs): Promise<McpToolResult> {
        return this.callTool("set_persona_scopes", args);
    }

    /** Look up detailed documentation for a specific tool. */
    toolDocs(args: ToolDocsArgs): Promise<McpToolResult> {
        return this.callTool("tool_docs", args);
    }

    /**
     * Transcribe an audio file and save the transcript next to the original file.
     * Docs: https://docs.zocomputer.com/tools/transcribe-audio.md
     */
    transcribeAudio(args: TranscribeAudioArgs): Promise<McpToolResult> {
        return this.callTool("transcribe_audio", args);
    }

    /**
     * Transcribe audio from a video file and save the transcript next to the original file.
     * Docs: https://docs.zocomputer.com/tools/transcribe-video.md
     */
    transcribeVideo(args: TranscribeVideoArgs): Promise<McpToolResult> {
        return this.callTool("transcribe_video", args);
    }

    /**
     * Undo the last change to a space route, restoring the previous version.
     *
     * This can undo code changes and also undo deletions (re-creating the route).
     * History persists across host reboots.
     *
     * Args:
     *     path: Route path to undo, e.g. '/about' or '/api/hello'.
     * Docs: https://docs.zocomputer.com/tools/undo-space-route.md
     */
    undoSpaceRoute(args: UndoSpaceRouteArgs): Promise<McpToolResult> {
        return this.callTool("undo_space_route", args);
    }

    /**
     * Unpublish a Zo Site, removing its dedicated URL.
     * Docs: https://docs.zocomputer.com/tools/unpublish-site.md
     */
    unpublishSite(args: UnpublishSiteArgs): Promise<McpToolResult> {
        return this.callTool("unpublish_site", args);
    }

    /**
     * Copy a file from the workspace to the user's zo.space assets.
     *
     * Assets are served at their asset_path, e.g. asset_path='/images/logo.png' is accessible at '/images/logo.png'.
     * Reference in pages: <img src="/images/logo.png" />
     *
     * Args:
     *     source_file: Path to the source file in the workspace, e.g. '/home/workspace/images/logo.png'.
     *     asset_path: URL path where the asset will be served, starting with '/', e.g. '/images/logo.png'.
     * Docs: https://docs.zocomputer.com/tools/update-space-asset.md
     */
    updateSpaceAsset(args: UpdateSpaceAssetArgs): Promise<McpToolResult> {
        return this.callTool("update_space_asset", args);
    }

    /**
     * Update space settings — either globally or for a single page route.
     *
     * By default (`path=""`) the call updates space-wide settings stored in
     * `site-settings.json`. Pass a route path (e.g. `path="/"` for the home page
     * or `path="/about"`) to apply the change as a per-page override that
     * inherits from the space defaults when unset.
     *
     * Only provided arguments are changed; omitted arguments keep their current
     * values. Pass "default" for any string field to clear it (revert to the
     * space default when path is set, revert to the built-in default when path
     * is empty). Triggers a zo-space server restart so changes take effect
     * immediately.
     *
     * Per-page overrides only support `site_title`, `site_description`,
     * `og_image_url`, and `noindex` — they map onto `page_title`,
     * `page_description`, `page_og_image_url`, and `page_noindex` ("block" /
     * "allow"). The other fields apply space-globally only and will be
     * rejected if combined with a non-empty `path`.
     *
     * Args:
     *     path: Empty string for space-global settings (default), or a route
     *         path like "/" (home) or "/about" to update that page's metadata
     *         overrides. Note: "" is the global sentinel and is distinct from
     *         "/" which is the home route.
     *     site_title: Title override. Pass "default" to reset/clear.
     *     site_description: Meta description. Pass "default" to reset/clear.
     *     og_image_url: Asset path for OG image (e.g. "/assets/og.png"). Must
     *         be a space asset, not an external URL. Pass "default" to revert.
     *     favicon_url: Asset path for favicon. Space-global only.
     *     custom_head_html: HTML injected into <head>. Space-global only.
     *     robots_txt: Custom robots.txt content. Space-global only.
     *     noindex: "true" adds noindex/nofollow; "false" removes it; "default"
     *         clears any per-page override (and inherits from the space).
     *     custom_404_route: Route path for custom 404 page. Space-global only.
     *     lang: HTML lang attribute value. Space-global only.
     *     atproto_did: AT Protocol DID for domain verification. Space-global only.
     * Docs: https://docs.zocomputer.com/tools/update-space-settings.md
     */
    updateSpaceSettings(args: UpdateSpaceSettingsArgs): Promise<McpToolResult> {
        return this.callTool("update_space_settings", args);
    }

    /**
     * Update a managed user service on your Zo server. Only specify the fields you want to change; omitted fields keep their existing values. Always restarts the service process.
     * Docs: https://docs.zocomputer.com/tools/update-user-service.md
     */
    updateUserService(args: UpdateUserServiceArgs): Promise<McpToolResult> {
        return this.callTool("update_user_service", args);
    }

    /**
     * Update a user setting (name or bio) in Zo.
     * Docs: https://docs.zocomputer.com/tools/update-user-settings.md
     */
    updateUserSettings(args: UpdateUserSettingsArgs): Promise<McpToolResult> {
        return this.callTool("update_user_settings", args);
    }

    /**
     * Work with the user's connected Gmail account.
     * Docs: https://docs.zocomputer.com/tools/use-app-gmail.md
     */
    useAppGmail(args: UseAppGmailArgs): Promise<McpToolResult> {
        return this.callTool("use_app_gmail", args);
    }

    /**
     * Interact with the current page using an AI agent.
     * Docs: https://docs.zocomputer.com/tools/use-webpage.md
     */
    useWebpage(args: UseWebpageArgs): Promise<McpToolResult> {
        return this.callTool("use_webpage", args);
    }

    /**
     * View the current page in the browser and get its content plus a screenshot.
     * Docs: https://docs.zocomputer.com/tools/view-webpage.md
     */
    viewWebpage(args: ViewWebpageArgs): Promise<McpToolResult> {
        return this.callTool("view_webpage", args);
    }

    /**
     * Perform an in-depth web search using a more powerful search engine.
     * Docs: https://docs.zocomputer.com/tools/web-research.md
     */
    webResearch(args: WebResearchArgs): Promise<McpToolResult> {
        return this.callTool("web_research", args);
    }

    /**
     * Search the web using a search engine.
     * Docs: https://docs.zocomputer.com/tools/web-search.md
     */
    webSearch(args: WebSearchArgs): Promise<McpToolResult> {
        return this.callTool("web_search", args);
    }

    /**
     * Create a new file or rewrite an existing one with the provided content.
     * Docs: https://docs.zocomputer.com/tools/write-file.md
     */
    writeFile(args: WriteFileArgs): Promise<McpToolResult> {
        return this.callTool("write_file", args);
    }

    /**
     * Create a new route or fully rewrite an existing one in the user's zo.space site.
     *
     * See <capabilities> for architecture details, examples, and styling guidance.
     *
     * IMPORTANT: For edits to an existing route, use `edit_space_route` instead — it sends only the changed sections and avoids re-transmitting the whole file. Only use `write_space_route` when creating a new route or intentionally replacing all of the existing code.
     * Docs: https://docs.zocomputer.com/tools/write-space-route.md
     */
    writeSpaceRoute(args: WriteSpaceRouteArgs): Promise<McpToolResult> {
        return this.callTool("write_space_route", args);
    }

    /**
     * Search X (Twitter) for posts and users matching a query.
     *
     * This tool utilizes a subagent with access to the X API.
     *
     * Args:
     *     query: Natural language prompt describing what to find on X.
     * Docs: https://docs.zocomputer.com/tools/x-search.md
     */
    xSearch(args: XSearchArgs): Promise<McpToolResult> {
        return this.callTool("x_search", args);
    }
}
